/*
 * This file is generated by jOOQ.
 */

package scrapper.domain.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Comment implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private OffsetDateTime creationDate;
    private Integer linkId;

    public Comment() {
    }

    public Comment(Comment value) {
        this.id = value.id;
        this.creationDate = value.creationDate;
        this.linkId = value.linkId;
    }

    @ConstructorProperties({"id", "creationDate", "linkId"})
    public Comment(
        @NotNull Long id,
        @Nullable OffsetDateTime creationDate,
        @NotNull Integer linkId
    ) {
        this.id = id;
        this.creationDate = creationDate;
        this.linkId = linkId;
    }

    /**
     * Getter for <code>COMMENT.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>COMMENT.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>COMMENT.CREATION_DATE</code>.
     */
    @Nullable
    public OffsetDateTime getCreationDate() {
        return this.creationDate;
    }

    /**
     * Setter for <code>COMMENT.CREATION_DATE</code>.
     */
    public void setCreationDate(@Nullable OffsetDateTime creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * Getter for <code>COMMENT.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>COMMENT.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Integer linkId) {
        this.linkId = linkId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Comment other = (Comment) obj;
        if (this.id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!this.id.equals(other.id)) {
            return false;
        }
        if (this.creationDate == null) {
            if (other.creationDate != null) {
                return false;
            }
        } else if (!this.creationDate.equals(other.creationDate)) {
            return false;
        }
        if (this.linkId == null) {
            if (other.linkId != null) {
                return false;
            }
        } else if (!this.linkId.equals(other.linkId)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.creationDate == null) ? 0 : this.creationDate.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Comment (");

        sb.append(id);
        sb.append(", ").append(creationDate);
        sb.append(", ").append(linkId);

        sb.append(")");
        return sb.toString();
    }
}
