/*
 * This file is generated by jOOQ.
 */
package scrapper.domain.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PullRequest implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String title;
    private Integer linkId;

    public PullRequest() {}

    public PullRequest(PullRequest value) {
        this.id = value.id;
        this.title = value.title;
        this.linkId = value.linkId;
    }

    @ConstructorProperties({ "id", "title", "linkId" })
    public PullRequest(
        @NotNull Long id,
        @NotNull String title,
        @NotNull Integer linkId
    ) {
        this.id = id;
        this.title = title;
        this.linkId = linkId;
    }

    /**
     * Getter for <code>PULL_REQUEST.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>PULL_REQUEST.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>PULL_REQUEST.TITLE</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 1000000000)
    @NotNull
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>PULL_REQUEST.TITLE</code>.
     */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    /**
     * Getter for <code>PULL_REQUEST.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>PULL_REQUEST.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Integer linkId) {
        this.linkId = linkId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PullRequest other = (PullRequest) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PullRequest (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(linkId);

        sb.append(")");
        return sb.toString();
    }
}
