/*
 * This file is generated by jOOQ.
 */

package scrapper.domain.jooq.tables;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import scrapper.domain.jooq.DefaultSchema;
import scrapper.domain.jooq.Keys;
import scrapper.domain.jooq.tables.records.PullRequestRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PullRequest extends TableImpl<PullRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PULL_REQUEST</code>
     */
    public static final PullRequest PULL_REQUEST = new PullRequest();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<PullRequestRecord> getRecordType() {
        return PullRequestRecord.class;
    }

    /**
     * The column <code>PULL_REQUEST.ID</code>.
     */
    public final TableField<PullRequestRecord, Long> ID =
        createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PULL_REQUEST.TITLE</code>.
     */
    public final TableField<PullRequestRecord, String> TITLE =
        createField(DSL.name("TITLE"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>PULL_REQUEST.LINK_ID</code>.
     */
    public final TableField<PullRequestRecord, Integer> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    private PullRequest(Name alias, Table<PullRequestRecord> aliased) {
        this(alias, aliased, null);
    }

    private PullRequest(Name alias, Table<PullRequestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PULL_REQUEST</code> table reference
     */
    public PullRequest(String alias) {
        this(DSL.name(alias), PULL_REQUEST);
    }

    /**
     * Create an aliased <code>PULL_REQUEST</code> table reference
     */
    public PullRequest(Name alias) {
        this(alias, PULL_REQUEST);
    }

    /**
     * Create a <code>PULL_REQUEST</code> table reference
     */
    public PullRequest() {
        this(DSL.name("PULL_REQUEST"), null);
    }

    public <O extends Record> PullRequest(Table<O> child, ForeignKey<O, PullRequestRecord> key) {
        super(child, key, PULL_REQUEST);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<PullRequestRecord> getPrimaryKey() {
        return Keys.PULL_REQUEST_PKEY;
    }

    @Override
    @NotNull
    public List<ForeignKey<PullRequestRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_5);
    }

    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null) {
            _link = new Link(this, Keys.CONSTRAINT_5);
        }

        return _link;
    }

    @Override
    @NotNull
    public PullRequest as(String alias) {
        return new PullRequest(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public PullRequest as(Name alias) {
        return new PullRequest(alias, this);
    }

    @Override
    @NotNull
    public PullRequest as(Table<?> alias) {
        return new PullRequest(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public PullRequest rename(String name) {
        return new PullRequest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public PullRequest rename(Name name) {
        return new PullRequest(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public PullRequest rename(Table<?> name) {
        return new PullRequest(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
        Class<U> toType,
        Function3<? super Long, ? super String, ? super Integer, ? extends U> from
    ) {
        return convertFrom(toType, Records.mapping(from));
    }
}
