app:
  scheduler:
    enable: true
    interval: PT10S
    force-check-delay: PT10S

spring:
  application:
    name: scrapper
client:
  github:
    baseurl: https://api.github.com
  stack:
    baseurl: https://api.stackexchange.com/2.3/

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
