app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper
client:
  github:
    baseurl: https://api.github.com
  stack:
    baseurl: https://api.stackexchange.com/2.3/
  bot:
    baseurl: http://localhost:8090
springdoc:
  swagger-ui:
    path: /swagger-ui
server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
