app:
  telegram-token: ${TELEGRAMTOKEN}
springdoc:
  swagger-ui:
    path: /swagger-ui
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
client:
  scrapper:
    baseurl: http://localhost:8081
server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
