/*
 * This file is generated by jOOQ.
 */

package scrapper.domain.jooq;

import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import scrapper.domain.jooq.tables.Answer;
import scrapper.domain.jooq.tables.Branch;
import scrapper.domain.jooq.tables.Chat;
import scrapper.domain.jooq.tables.ChatLink;
import scrapper.domain.jooq.tables.Comment;
import scrapper.domain.jooq.tables.Link;
import scrapper.domain.jooq.tables.PullRequest;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>ANSWER</code>.
     */
    public final Answer ANSWER = Answer.ANSWER;

    /**
     * The table <code>BRANCH</code>.
     */
    public final Branch BRANCH = Branch.BRANCH;

    /**
     * The table <code>CHAT</code>.
     */
    public final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>CHAT_LINK</code>.
     */
    public final ChatLink CHAT_LINK = ChatLink.CHAT_LINK;

    /**
     * The table <code>COMMENT</code>.
     */
    public final Comment COMMENT = Comment.COMMENT;

    /**
     * The table <code>LINK</code>.
     */
    public final Link LINK = Link.LINK;

    /**
     * The table <code>PULL_REQUEST</code>.
     */
    public final PullRequest PULL_REQUEST = PullRequest.PULL_REQUEST;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }

    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Answer.ANSWER,
            Branch.BRANCH,
            Chat.CHAT,
            ChatLink.CHAT_LINK,
            Comment.COMMENT,
            Link.LINK,
            PullRequest.PULL_REQUEST
        );
    }
}
