/*
 * This file is generated by jOOQ.
 */
package scrapper.domain.jooq.tables.records;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import scrapper.domain.jooq.tables.Branch;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BranchRecord extends UpdatableRecordImpl<BranchRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>BRANCH.NAME</code>.
     */
    public void setName(@NotNull String value) {
        set(0, value);
    }

    /**
     * Getter for <code>BRANCH.NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 1000000000)
    @NotNull
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>BRANCH.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>BRANCH.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getLinkId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return Branch.BRANCH.NAME;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return Branch.BRANCH.LINK_ID;
    }

    @Override
    @NotNull
    public String component1() {
        return getName();
    }

    @Override
    @NotNull
    public Integer component2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public String value1() {
        return getName();
    }

    @Override
    @NotNull
    public Integer value2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public BranchRecord value1(@NotNull String value) {
        setName(value);
        return this;
    }

    @Override
    @NotNull
    public BranchRecord value2(@NotNull Integer value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public BranchRecord values(@NotNull String value1, @NotNull Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BranchRecord
     */
    public BranchRecord() {
        super(Branch.BRANCH);
    }

    /**
     * Create a detached, initialised BranchRecord
     */
    @ConstructorProperties({ "name", "linkId" })
    public BranchRecord(@NotNull String name, @NotNull Integer linkId) {
        super(Branch.BRANCH);

        setName(name);
        setLinkId(linkId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BranchRecord
     */
    public BranchRecord(scrapper.domain.jooq.tables.pojos.Branch value) {
        super(Branch.BRANCH);

        if (value != null) {
            setName(value.getName());
            setLinkId(value.getLinkId());
            resetChangedOnNotNull();
        }
    }
}
