/*
 * This file is generated by jOOQ.
 */

package scrapper.domain.jooq.tables.records;

import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import scrapper.domain.jooq.tables.Comment;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CommentRecord extends UpdatableRecordImpl<CommentRecord>
    implements Record3<Long, OffsetDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>COMMENT.ID</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>COMMENT.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>COMMENT.CREATION_DATE</code>.
     */
    public void setCreationDate(@Nullable OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>COMMENT.CREATION_DATE</code>.
     */
    @Nullable
    public OffsetDateTime getCreationDate() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>COMMENT.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>COMMENT.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getLinkId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, OffsetDateTime, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, OffsetDateTime, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Comment.COMMENT.ID;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field2() {
        return Comment.COMMENT.CREATION_DATE;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return Comment.COMMENT.LINK_ID;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @Nullable
    public OffsetDateTime component2() {
        return getCreationDate();
    }

    @Override
    @NotNull
    public Integer component3() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @Nullable
    public OffsetDateTime value2() {
        return getCreationDate();
    }

    @Override
    @NotNull
    public Integer value3() {
        return getLinkId();
    }

    @Override
    @NotNull
    public CommentRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public CommentRecord value2(@Nullable OffsetDateTime value) {
        setCreationDate(value);
        return this;
    }

    @Override
    @NotNull
    public CommentRecord value3(@NotNull Integer value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public CommentRecord values(@NotNull Long value1, @Nullable OffsetDateTime value2, @NotNull Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentRecord
     */
    public CommentRecord() {
        super(Comment.COMMENT);
    }

    /**
     * Create a detached, initialised CommentRecord
     */
    @ConstructorProperties({"id", "creationDate", "linkId"})
    public CommentRecord(@NotNull Long id, @Nullable OffsetDateTime creationDate, @NotNull Integer linkId) {
        super(Comment.COMMENT);

        setId(id);
        setCreationDate(creationDate);
        setLinkId(linkId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CommentRecord
     */
    public CommentRecord(scrapper.domain.jooq.tables.pojos.Comment value) {
        super(Comment.COMMENT);

        if (value != null) {
            setId(value.getId());
            setCreationDate(value.getCreationDate());
            setLinkId(value.getLinkId());
            resetChangedOnNotNull();
        }
    }
}
