/*
 * This file is generated by jOOQ.
 */

package scrapper.domain.jooq.tables.records;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import scrapper.domain.jooq.tables.Link;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class LinkRecord extends UpdatableRecordImpl<LinkRecord>
    implements Record4<Integer, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINK.ID</code>.
     */
    public void setId(@Nullable Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINK.ID</code>.
     */
    @Nullable
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>LINK.NAME</code>.
     */
    public void setName(@Nullable String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINK.NAME</code>.
     */
    @Size(max = 1000000000)
    @Nullable
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LINK.CREATED_AT</code>.
     */
    public void setCreatedAt(@Nullable OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINK.CREATED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>LINK.LAST_UPDATED_AT</code>.
     */
    public void setLastUpdatedAt(@Nullable OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>LINK.LAST_UPDATED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getLastUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Integer, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row4<Integer, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return Link.LINK.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Link.LINK.NAME;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field3() {
        return Link.LINK.CREATED_AT;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field4() {
        return Link.LINK.LAST_UPDATED_AT;
    }

    @Override
    @Nullable
    public Integer component1() {
        return getId();
    }

    @Override
    @Nullable
    public String component2() {
        return getName();
    }

    @Override
    @Nullable
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    @Nullable
    public OffsetDateTime component4() {
        return getLastUpdatedAt();
    }

    @Override
    @Nullable
    public Integer value1() {
        return getId();
    }

    @Override
    @Nullable
    public String value2() {
        return getName();
    }

    @Override
    @Nullable
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    @Nullable
    public OffsetDateTime value4() {
        return getLastUpdatedAt();
    }

    @Override
    @NotNull
    public LinkRecord value1(@Nullable Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value2(@Nullable String value) {
        setName(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value3(@Nullable OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value4(@Nullable OffsetDateTime value) {
        setLastUpdatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord values(
        @Nullable Integer value1,
        @Nullable String value2,
        @Nullable OffsetDateTime value3,
        @Nullable OffsetDateTime value4
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    @ConstructorProperties({"id", "name", "createdAt", "lastUpdatedAt"})
    public LinkRecord(
        @Nullable Integer id,
        @Nullable String name,
        @Nullable OffsetDateTime createdAt,
        @Nullable OffsetDateTime lastUpdatedAt
    ) {
        super(Link.LINK);

        setId(id);
        setName(name);
        setCreatedAt(createdAt);
        setLastUpdatedAt(lastUpdatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    public LinkRecord(scrapper.domain.jooq.tables.pojos.Link value) {
        super(Link.LINK);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setCreatedAt(value.getCreatedAt());
            setLastUpdatedAt(value.getLastUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
