/*
 * This file is generated by jOOQ.
 */

package scrapper.domain.jooq.tables.records;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import scrapper.domain.jooq.tables.PullRequest;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PullRequestRecord extends UpdatableRecordImpl<PullRequestRecord>
    implements Record3<Long, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PULL_REQUEST.ID</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PULL_REQUEST.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PULL_REQUEST.TITLE</code>.
     */
    public void setTitle(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PULL_REQUEST.TITLE</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 1000000000)
    @NotNull
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PULL_REQUEST.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PULL_REQUEST.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getLinkId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return PullRequest.PULL_REQUEST.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return PullRequest.PULL_REQUEST.TITLE;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return PullRequest.PULL_REQUEST.LINK_ID;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getTitle();
    }

    @Override
    @NotNull
    public Integer component3() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getTitle();
    }

    @Override
    @NotNull
    public Integer value3() {
        return getLinkId();
    }

    @Override
    @NotNull
    public PullRequestRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public PullRequestRecord value2(@NotNull String value) {
        setTitle(value);
        return this;
    }

    @Override
    @NotNull
    public PullRequestRecord value3(@NotNull Integer value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public PullRequestRecord values(@NotNull Long value1, @NotNull String value2, @NotNull Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PullRequestRecord
     */
    public PullRequestRecord() {
        super(PullRequest.PULL_REQUEST);
    }

    /**
     * Create a detached, initialised PullRequestRecord
     */
    @ConstructorProperties({"id", "title", "linkId"})
    public PullRequestRecord(@NotNull Long id, @NotNull String title, @NotNull Integer linkId) {
        super(PullRequest.PULL_REQUEST);

        setId(id);
        setTitle(title);
        setLinkId(linkId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PullRequestRecord
     */
    public PullRequestRecord(scrapper.domain.jooq.tables.pojos.PullRequest value) {
        super(PullRequest.PULL_REQUEST);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setLinkId(value.getLinkId());
            resetChangedOnNotNull();
        }
    }
}
